language: java
jdk:
- openjdk7
branches:
  only:
    - master
script: mvn install
deploy:
  provider: s3
  access_key_id: AKIAJONSK6SH5DZ5R7LA
  secret_access_key:
    secure: gWbvdJqCLGqU3OxN8EAE2ahasWSWwZ755EbnMtjh3sFjvjYwTc+5v9ih4gOc8eCzVAwCFUBbV5BbLwB98Z4rmXv+FJwddbQ1WccLMAflJYLzZabeBlovdafNwYVkZd2Cig/ZsA22XcnvyPS0ajcBL8lweiu4c4ARk4AUQNSR1v0=
  bucket: deploy.magnetic.io
  upload-dir: snapshots
  local-dir: target/install
  region: eu-west-1
  endpoint: s3-eu-west-1.amazonaws.com
  skip_cleanup: true
  on:
    repo: tnolet/vamp_bootstrap
